apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-app
  namespace: hpa-demo
  labels:
    app: hpa-demo-app
spec:
  selector:
    app: hpa-demo-app
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: ClusterIP
